name: Create Expo Module

on:
  push:
    branches: [main, 'sdk-*']
    paths:
      - .github/workflows/create-expo-module.yml
      - packages/create-expo-module/**
      - pnpm-lock.yaml
  pull_request:
    paths:
      - .github/workflows/create-expo-module.yml
      - packages/create-expo-module/**
      - pnpm-lock.yaml
  schedule:
    - cron: 0 14 * * *

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    if: github.event_name != 'schedule' || github.repository == 'expo/expo'
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        node: [20, 22]
    steps:
      - name: 👀 Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v4
        with:
          fetch-depth: 100
      - name: ⬇️ Fetch commits from base branch
        run: git fetch origin ${{ github.event.before || github.base_ref || 'main' }}:${{ github.event.before || github.base_ref || 'main' }} --depth 100
        if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
      - name: 🏗️ Setup pnpm
        uses: pnpm/action-setup@ea17c68df8912ef543352723c149a84f56e3d413 # v6.1.0
        with:
          version: 10
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'
      - name: 📦 Install node modules in root dir
        run: pnpm install --frozen-lockfile
      - name: 🛠 Build create-expo-module
        run: pnpm run prepublishOnly
        working-directory: packages/create-expo-module
      - name: 🧪 E2E Test create-expo-module
        run: pnpm test:e2e
        working-directory: packages/create-expo-module
