name: iOS Unit Tests

on:
  workflow_dispatch: {}
  pull_request:
    paths:
      - .github/workflows/ios-unit-tests.yml
      - apps/expo-go/ios/**
      - packages/**/ios/**
      - apps/native-tests/ios/**
      - tools/src/dynamic-macros/**
      - tools/src/commands/IosGenerateDynamicMacros.ts
      - tools/src/commands/IosNativeUnitTests.ts
      - tools/src/commands/NativeUnitTests.ts
      - secrets/**
      - fastlane/**
      - Gemfile.lock
      - '!packages/@expo/cli/**'
  push:
    branches: [main]
    paths:
      - .github/workflows/ios-unit-tests.yml
      - apps/expo-go/ios/**
      - packages/**/ios/**
      - tools/src/dynamic-macros/**
      - tools/src/commands/IosGenerateDynamicMacros.ts
      - tools/src/commands/IosNativeUnitTests.ts
      - tools/src/commands/NativeUnitTests.ts
      - secrets/**
      - fastlane/**
      - Gemfile.lock
      - '!packages/@expo/cli/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-26
    timeout-minutes: 75
    steps:
      - name: 👀 Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v4
        with:
          submodules: true
      - name: 🔨 Switch to Xcode 26.4.1
        run: sudo xcode-select --switch /Applications/Xcode_26.4.1.app
      - name: ➕ Add `bin` to GITHUB_PATH
        run: echo "$(pwd)/bin" >> $GITHUB_PATH
      - name: 💎 Setup Ruby and install gems
        uses: ruby/setup-ruby@14594264cd68ce8a2345dd349bc3d138a4ef85c8 # v1
        with:
          bundler-cache: true
          ruby-version: 3.2.2
      - name: 🧹 Cleanup unused simulator runtimes
        run: |
          xcrun simctl list devices -j | jq -r '.devices | to_entries[] | select(.key | contains("iOS") | not) | .value[].udid' | xargs -r -n1 xcrun simctl delete
          xcrun simctl list devices --json
          xcrun simctl erase all
          xcrun simctl shutdown all
          sudo xcodebuild -runFirstLaunch
      - name: 🔨 Install pnpm
        uses: pnpm/action-setup@ea17c68df8912ef543352723c149a84f56e3d413 # v6.1.0
        with:
          version: 10
      - name: 🔨 Setup Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 22
          cache: 'pnpm'
      - name: ♻️ Restore caches
        uses: ./.github/actions/expo-caches
        id: expo-caches
        with:
          native-tests-pods: 'true'
      - name: 📦 Install node modules
        run: pnpm install --frozen-lockfile
      - name: 🥥 Install CocoaPods in `apps/native-tests/ios`
        if: steps.expo-caches.outputs.bare-expo-pods-hit != 'true'
        run: pod install
        env:
          RCT_USE_PREBUILT_RNCORE: 1
          RCT_USE_RN_DEP: 1
        working-directory: apps/native-tests/ios
      - name: 🧪 Run native iOS unit tests
        timeout-minutes: 30
        env:
          FASTLANE_SKIP_UPDATE_CHECK: '1'
          FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: 30
          FASTLANE_XCODEBUILD_SETTINGS_RETRIES: 8
        run: pnpm expotools native-unit-tests --platform ios
      - name: 📤 Upload xcresult
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ios-unit-tests-results
          path: /tmp/ios-unit-tests-results
